(broken) examples: grid_graph_example: Remove "using namespace boost".
To demonstrate that the boost::grid_graph API is currently unusable
without using "using namespace boost".

This causes the following compiler errors, because these are actually member methods
of the grid_graph class, not functions in the boost namespace.
When we call just num_vertices(graph), instead of boost::num_vertices(graph), the
compiler finds the member method via argument dependent lookup.

grid_graph_example.cpp:34:25: error: no member named 'num_vertices' in namespace 'boost'
       v_index < boost::num_vertices(graph); ++v_index) {
                 ~~~~~~~^
grid_graph_example.cpp:38:53: error: no member named 'vertex' in namespace 'boost'
      boost::get(boost::vertex_index, graph, boost::vertex(v_index, graph)) << std::endl;
                                             ~~~~~~~^
grid_graph_example.cpp:48:51: error: no member named 'edge_at' in namespace 'boost'
      boost::get(boost::edge_index, graph, boost::edge_at(e_index, graph)) << std::endl;
                                           ~~~~~~~^
grid_graph_example.cpp:65:30: error: no member named 'vertex' in namespace 'boost'
  auto first_vertex = boost::vertex(0, graph);